name: backfill
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3.7
  - mkl
  - numba
  - numexpr
  - numpy
  - scipy
  - scikit-learn
  - statsmodels
  - pyarrow >=1.0
  - pandas >=1.1
  - pandas_market_calendars
  - ipython
  - jupyterlab
  - dask
  - cachey
  - graphviz
  - bokeh
  - prefect[viz, gcp, aws]
  - requests
  - s3fs
  - trio
  - tqdm
  - pip
  - pip:
    - trio_websocket
    - pandas-bokeh
